apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: kubescape
    app.kubernetes.io/name: kubescape
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: prometheus.v1
  name: kubescape
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: kubescape
      app.kubernetes.io/name: kubescape
      app.kubernetes.io/part-of: kube-prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/component: kubescape
        app.kubernetes.io/name: kubescape
        app.kubernetes.io/part-of: kube-prometheus
        app.kubernetes.io/version: prometheus.v1
    spec:
      containers:
      - command:
        - kubescape
        env:
        - name: KS_RUN_PROMETHEUS_SERVER
          value: "true"
        - name: KS_DEFAULT_CONFIGMAP_NAMESPACE
          value: monitoring
        image: quay.io/armosec/kubescape:prometheus.v1
        name: kubescape
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 10m
            memory: 100Mi
      serviceAccountName: kubescape
