apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: kubescape
    app.kubernetes.io/name: kubescape
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: prometheus.v1
  name: kubescape
  namespace: monitoring
spec:
  endpoints:
  - interval: 120s
    port: metrics
    scrapeTimeout: 120s
  selector:
    matchLabels:
      app.kubernetes.io/component: kubescape
      app.kubernetes.io/name: kubescape
      app.kubernetes.io/part-of: kube-prometheus
